### ISSUE TITLE
View completely obstructed when in blocks in spectator mode

### ISSUE THREAD

**Issue by kosakriszi** [DaFlight/DaFlightLiteloader#16]
When I fly into blocks in spectator mode, I am now able to clip into blocks, but my view is completely obstructed. The effect is very similar to being stuck inside blocks while in creative or survival.

![](http://puu.sh/j97kQ/a4ce311232.jpg)

**Comment by dags-** [comment]
Woops yeah, looks like I left a line of testing code in on commit 6bb653463c028403bdfd239d9ffac01d0ac04e24 that messes things up

ref: 
https://github.com/DaFlight/DaFlightLiteloader/blob/6bb653463c028403bdfd239d9ffac01d0ac04e24/java/me/dags/daflightliteloader/minecraft/extended/EntityDaFlyer.java#L44

Should be fixed in r6
